### ISSUE TITLE
aways build error

### ISSUE THREAD

**Issue by ghost** [dirkolbrich/hugo-theme-tailwindcss-starter#1]
Building sites … ERROR 2019/06/06 16:47:03 error: failed to transform resource: POSTCSS: failed to transform "css/styles.css" (text/css): PostCSS not found; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/

I have used npm install in theme folder.

**Comment by dirkolbrich** [comment]
You have to install `postcss-cli` globally, as mentioned in the docs.

> Hugo Pipe’s PostCSS requires the postcss-cli JavaScript package to be installed in the environment (npm install -g postcss-cli) along with any PostCSS plugin(s) used (e.g., npm install -g autoprefixer).
