### ISSUE TITLE
error with postCSS

### ISSUE THREAD

**Issue by ghost** [dirkolbrich/hugo-theme-tailwindcss-starter#11]
hi, 

first, thank you for your theme.
in develoment mode my web site work but in production i have a problem.

> my repository : https://github.com/Shurikken/digitalefun

I have a probleme with postcss :

if i install 

```bash
npm install -g postcss-cli
npm install -g autoprefixer
```

my hugo web site don't work in development and in production in netlify

if i run my web site in production i have this error : 

```bash
Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css): resource "css/localhost/css/styles.css_f2054ba793222939610cd2936fa9ba1e" not found in file cache
```

i have this error in netlify 

```bash
4:43:54 PM: Build ready to start
4:43:57 PM: build-image version: 2dbd444fcdce00cf06325060a8238d5ae3e86774
4:43:57 PM: build-image tag: v3.3.7
4:43:57 PM: buildbot version: 11918e084194721d200458438c92ff8180b3b56c
4:43:57 PM: Fetching cached dependencies
4:43:57 PM: Starting to download cache of 254.9KB
4:43:57 PM: Finished downloading cache in 91.186142ms
4:43:57 PM: Starting to extract cache
4:43:57 PM: Failed to fetch cache, continuing with build
4:43:57 PM: Starting to prepare the repo for build
4:43:58 PM: No cached dependencies found. Cloning fresh repo
4:43:58 PM: git clone https://github.com/Shurikken/digitalefun
4:43:58 PM: Preparing Git Reference refs/heads/master
4:43:59 PM: Starting build script
4:43:59 PM: Installing dependencies
4:44:00 PM: v10.19.0 is already installed.
4:44:01 PM: Now using node v10.19.0 (npm v6.13.4)
4:44:01 PM: Attempting ruby version 2.6.2, read from environment
4:44:03 PM: Using ruby version 2.6.2
4:44:03 PM: Using PHP version 5.6
4:44:03 PM: Started restoring cached go cache
4:44:03 PM: Finished restoring cached go cache
4:44:03 PM: unset GOOS;
4:44:03 PM: unset GOARCH;
4:44:03 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
4:44:03 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
4:44:03 PM: go version >&2;
4:44:03 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
4:44:03 PM: go version go1.12 linux/amd64
4:44:03 PM: Installing missing commands
4:44:03 PM: Verify run directory
4:44:03 PM: Executing user command: hugo --gc --minify
4:44:03 PM: Building sites …
4:44:03 PM: ERROR 2020/03/21 15:44:03 error: failed to transform resource: POSTCSS: failed to transform "css/styles.css" (text/css): PostCSS not found; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/
4:44:03 PM: Total in 13 ms
4:44:03 PM: Error: Error building site: logged 1 error(s)
4:44:03 PM: Skipping functions preparation step: no functions directory set
4:44:03 PM: Caching artifacts
4:44:03 PM: Started saving pip cache
4:44:03 PM: Finished saving pip cache
4:44:03 PM: Started saving emacs cask dependencies
4:44:03 PM: Finished saving emacs cask dependencies
4:44:03 PM: Started saving maven dependencies
4:44:03 PM: Finished saving maven dependencies
4:44:03 PM: Started saving boot dependencies
4:44:03 PM: Finished saving boot dependencies
4:44:03 PM: Started saving go dependencies
4:44:03 PM: Finished saving go dependencies
4:44:06 PM: Error running command: Build script returned non-zero exit code: 255
4:44:06 PM: Failing build: Failed to build site
4:44:06 PM: failed during stage 'building site': Build script returned non-zero exit code: 255
4:44:06 PM: Finished processing build request in 9.598170711s
```

could you help me please ? 
Thank you very munch

**Comment by dirkolbrich** [comment]
Hey,

this looks like an error with global NPM package installation on Netfly. As I never worked with or deployed to Netfly, I can not help you with this problem.

My guess: this error line indicates, that `postcss-cli` is not correctly installed on Netfly.

```
4:44:03 PM: ERROR 2020/03/21 15:44:03 error: failed to transform resource: POSTCSS: failed to transform "css/styles.css" (text/css): PostCSS not found; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/
```

Did you installed the global NPM packages locally on your machine, or on Netfly?

```
npm install -g postcss-cli
npm install -g autoprefixer
```

**Comment by ghost** [comment]
hi 
if i install this packages on my imac, i have an error and my hugo don't work in dev or production.
and i use sudo if i want install this because without sudo ! can't install this.
i don't install in netlify.

**Comment by dirkolbrich** [comment]
You mentioned Netlify in your initial post twice, and your error log output  seems to be from the Netlify installation process. 

If the installation of this package does not work on your local machine, please post your exact commands and steps you took. 

See also this closed issue: https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter/issues/10

**Comment by ghost** [comment]
hi @dirkolbrich  i found where is problem.

netlify don't know corectly script if else  environnement dev / production in partial head.html 

if i delete script dev environnement my hugo site run in netlify

**Comment by dirkolbrich** [comment]
I tinkered a little with an example setup and added a [Deploy to Netlify](https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter#deploy-to-netlify) section to the README. Maybe this helps with your problem.

**Comment by ghost** [comment]
hi @dirkolbrich thank you very much for your work.
i will testing with netlify.
I see with hugo templateMetrics build is very slow  
it is same for you ? 

`  10.437281567s  5.218640783s  5.220147189s      2  _default/single.html
  10.435746982s  1.490820997s  5.218671267s      7  partials/head.html
      2.20153ms     550.382µs     857.204µs      4  _internal/_default/rss.xml
     1.844606ms     614.868µs     675.056µs      3  _default/list.html
     1.222774ms     174.682µs     344.994µs      7  partials/header.html
      950.182µs     950.182µs     950.182µs      1  _internal/_default/sitemap.xml
      662.196µs     662.196µs     662.196µs      1  404.html
      582.021µs     582.021µs     582.021µs      1  index.html
      200.674µs      28.667µs     116.016µs      7  partials/footer.html`

**Comment by ghost** [comment]
hi @dirkolbrich  i confirm your theme run in netlify server.
i have just later question for you : why  css work in master--domaine.netlify.com and  don"t work in domaine.netlify.com ?  why master-- before  netlify domaine ?

**Comment by dirkolbrich** [comment]
Because you specified your `baseURL` as that. Your build command probably looks like:

```
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
```

`-b` signals Hugo to use the following string as the specified baseURL, see the [Hugo flags explained](https://gohugo.io/commands/hugo_server/#options). `$DEPLOY_PRIME_URL` is a [Netlify build environment variable](https://docs.netlify.com/configure-builds/environment-variables/#deploy-urls-and-metadata) which results to `https://master--domaine.netlify.com` as your build from the master branch.

You should omit `-b $DEPLOY_PRIME_URL` as Netlify builds automatically from `master`. Just use

```
command = "hugo --gc --minify"
```
