### ISSUE TITLE
Missing head tag?

### ISSUE THREAD

**Issue by zorn** [dirkolbrich/hugo-theme-tailwindcss-starter#18]
Just getting started with this. Thanks so much!!

I think the template is missing the HTML `<head>` tag though.

layouts/_default/baseof.html

layouts/partials/head.html

I added mine in `baseof.html` to be consistent with the similar `<body>` tag.

**Comment by dirkolbrich** [comment]
Nope, not missing. All `<head>` tags are found in `partials/head.html`. They are included here:
https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter/blob/67c3b15c2034783be43944973fc9790e83950c55/layouts/_default/baseof.html#L3

**Comment by dirkolbrich** [comment]
Waaahhhhh, just saw it. You are right. Will fix it.
