### ISSUE TITLE
Question: How to update the theme

### ISSUE THREAD

**Issue by rockey5520** [dirkolbrich/hugo-theme-tailwindcss-starter#26]
Hi Dirk Olbrich,

I have used this theme you built a while ago when tailwind was at 1.4 now that I see you made changes to the code to make the theme work with 1.6 I want to update my site using this theme. 

What I am trying to understand is which of the files in this theme repo I need to merge with my site?

**Comment by dirkolbrich** [comment]
Sorry, I can not answer this equations as I don't know what other changes you made to this starter theme.

Please be aware: This theme is a starter setup theme to aid in developing Hugo themes using the Tailwind CSS framework. It is not a standalone theme ready to use.

I would suggest use the DIFF function of Github to see which files are different, than change them accordingly.
