### ISSUE TITLE
Tailwind 2 released!

### ISSUE THREAD

**Issue by iaminamcom** [dirkolbrich/hugo-theme-tailwindcss-starter#27]
Hi
Tailwind 2 released and I think you'd upgrade theme as well to get most out of Tailwind 2 release.

**Comment by dirkolbrich** [comment]
check the release status -> [v0.4.0](https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter/releases/tag/v0.4.0)

a note on this theme starter: This theme is a starter setup theme to aid in developing Hugo themes using the Tailwind CSS framework. It is not a standalone theme ready to use.

**Comment by iaminamcom** [comment]
Yes I know that. Then it's technically useless because of main reason by
updating things it break. There are major changes which break things and if
it's not working after then definitely what's the point of using it when
user has to configure it on his own.

At least you should mention that in readme file and tell folks it's not
compatible with latest versions. So they don't waste time on something
which is either outdated or broken when updating.
Thank you
