### ISSUE TITLE
@tailwindcss/typography classes missing after building

### ISSUE THREAD

**Issue by Vantablack** [dirkolbrich/hugo-theme-tailwindcss-starter#28]
## Issue Description

I found an issue where PurgeCSS is removing @tailwindcss/typography classes.

**blockquote does not have CSS**
| Production | Development |
|-|-|
| ![image](https://user-images.githubusercontent.com/8582659/104018464-c55cde80-51f4-11eb-8121-a09d7816895f.png) | ![image](https://user-images.githubusercontent.com/8582659/104018413-aeb68780-51f4-11eb-9785-7e5ac7c62838.png) |

**code does not have CSS**
| Production | Development |
|-|-|
| ![image](https://user-images.githubusercontent.com/8582659/104018760-56cc5080-51f5-11eb-99e5-9f6633bcb00b.png) | ![image](https://user-images.githubusercontent.com/8582659/104018798-65b30300-51f5-11eb-9d02-53c731d3b0fb.png) |

**I think there are other CSS classes that are not included.**

I compiled the `public` site using this command `hugo -s exampleSite --themesDir=../..`.

## What seems to work?

1. Editing `postcss.config.js`

```js
        ...(process.env.HUGO_ENVIRONMENT === 'production' ? [purgecss] : [])
```

removing this line from postcss.config.js works, but I get a large CSS file.

2. Manually adding a HTML element to prevent PurgeCSS from removing it

```html
<!-- layouts/index.html -->
{{ define "main" }}
<article class="text-center text-gray-700">
    <h1 class="font-serif font-extralight text-5xl text-gray-500">{{ .Title }}</h1>
    {{ .Content }}
    <div class="prose">
        <blockquote>hi</blockquote>
    </div>
</article>
{{ end }}
```
Adding a `div` with class `prose` with `blockquote` as it's child prevent `blockquote` CSS from being purged.

## How to Resolve?

It seems like `postcss.config.js` needs to be edited to whitelist `prose` classes, however I am not familiar with it and am still trying to figure out how to solve it.

In the meantime I'll leave this information here in case the author/anyone out there has a solution.

**Comment by dirkolbrich** [comment]
You are right. PurgeCSS does not see used .prose classes during build, as it only checks the layout template files. In these the markdown is not build yet., thus no classes to spare from purging.

I changed the postcss-purgecss extractor to the one used in the [Hugo docs](https://gohugo.io/hugo-pipes/postprocess/#css-purging-with-postcss).

Please try out branch [verify-issue28](https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter/tree/verify-issue28) and see if it works. At least it does on my machine™.

**Comment by Vantablack** [comment]
@dirkolbrich That was a really fast fix! Yes, following the Hugo docs on PostProcess did the trick!

I also realised that the parent repo needs to have the `writeStats` option turned on too?

**Comment by dirkolbrich** [comment]
Yes, it does. I added this option to `/exampleSite.config.toml`. Should mention it in the Readme.

**Comment by Vantablack** [comment]
@dirkolbrich Got it! Thank you so much for solving it so quickly!
