### ISSUE TITLE
Bad path for purge CSS

### ISSUE THREAD

**Issue by vrastilondrej** [dirkolbrich/hugo-theme-tailwindcss-starter#3]
I had problems with production css, probably because bad purge css path in config. I added themeDir variable and now it works.
`content: [themeDir + 'layouts/**/*.html'],`

**Comment by dirkolbrich** [comment]
Hi, could you be more specific on the system, settings and commands you used while encountering this error?

- Hugo version
- use of the theme starter within a theme package or directly within a hugo project
- exact command to build the site
- expected css and actual build css (include code snippet)

This would help to investigate this error and fix the starter theme for all use cases. Thanks

**Comment by dirkolbrich** [comment]
Found it. Thank you.
