### ISSUE TITLE
QUESTION: rebuild time

### ISSUE THREAD

**Issue by wackazong** [dirkolbrich/hugo-theme-tailwindcss-starter#33]
Hey there and thanks for setting up this package. One question: is it expected that every rebuild takes about 3 seconds? Hugo alone takes like 10ms, is the rest due to the POSTCSS magic? And if yes, can that be sped up somehow? From a developer perspective live reload with a 3s delay is quite a long wait IMHO.

**Comment by dirkolbrich** [comment]
Actually no, this is unusual. I personally have not experienced such a long delay during development. It works nearly instantaneous when I use this starter package, even if I add 10-20 pages.

How many many Pages and static files do you build? Do changed the setup in any form and maybe run the purge process on every rebuild?

**Comment by wackazong** [comment]
Hmm, tried from a fresh install and now it works as expected. Thanks for pointing out that this long build time is unusual. I am actually using hugo-theme-tailwindcss-starter as a theme, leaving the files in `layouts` as they are and adding new files in the `layouts` directory of my Hugo project. It works with that approach as well. I did not find out what is causing the issue in my starter project but I will post it here if I find out.
