### ISSUE TITLE
pin-b is not a valid tailwind class

### ISSUE THREAD

**Issue by wackazong** [dirkolbrich/hugo-theme-tailwindcss-starter#35]
https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter/blob/663fd9bf56c095d12103c603c9f8dcbc64277125/layouts/partials/footer.html#L1

**Comment by wackazong** [comment]
Therefore I guess it's just a typo?

**Comment by dirkolbrich** [comment]
Good catch. But it's not a typo. `pin-b`was a valid positioning class in [tailwindcss < v0.x](https://tailwindcss-v0.netlify.app//docs/positioning). I somehow missed the [change in v1.x](https://v1.tailwindcss.com/docs/upgrading-to-v1#9-replace-pin-side-with-top-left-bottom-right-inset-value). Will add a fix.
