### ISSUE TITLE
Publishing new theme

### ISSUE THREAD

**Issue by mukhtharcm** [dirkolbrich/hugo-theme-tailwindcss-starter#41]
Can I publish a theme created using this repo as the starter?

**Comment by dirkolbrich** [comment]
Yes sure, that's the purpose of this repo. Fork, delete the old git history and change the setup info to your liking.
It would be nice, if you could include a reference to this repo in the source, but this is not a must.

**Comment by mukhtharcm** [comment]
That's very kind of you man!
If I publish a theme with this, I'll definitely link it back!.
